### ISSUE TITLE
imbalanced threads

### ISSUE THREAD

**Issue by tkphd** [tkphd/trijunctionThreshold#1]
https://github.com/tkphd/trijunctionThreshold/blob/b268393b694bce2d859baf2c7550b9d46f586658/src/ideal/extra/graingrowth.cpp#L52

Change from 11520000 seeds to 11550720.

**Comment by tkphd** [comment]
@lucentdan this might resolve the crashing.

**Comment by lucentdan** [comment]
Thanks, will pull and try again.
